import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeadDocs from "./_components/HeadDocs";
import ScriptDoc from "./_components/ScriptDoc";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Go to Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <HeadDocs />

      <body className={inter.className}>
          {children}
      </body>

      <ScriptDoc />
    </html>
  );
}
