import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import HeadDocs from "../_components/HeadDocs";
import ScriptDoc from "../_components/ScriptDoc";
import TopHeader from "../_components/TopHeader";
import BottonHeader from "../_components/BottonHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Horigentel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <HeadDocs />

      <body className={inter.className}>
        <div className="container-scroller">
          <div className="horizontal-menu">
            <TopHeader />
            <BottonHeader />
          </div>
          {children}
        </div>
      </body>

      <ScriptDoc />
    </html>
  );
}
